name: Static Site

on:
  push:
    branches:
      - main  # Set a branch to deploy
      - gha-service-account
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: 'google-github-actions/auth@v2'
      
      # configure gcloud `setup-gcloud` automatically
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/421707276957/locations/global/workloadIdentityPools/github/providers/my-repo1'
          service_account: 'cs1660service@alpine-surge-413017.iam.gserviceaccount.com'

      # upload files to GCS
      - id: 'upload-static-files'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'public'
          destination: 'srj42bucket1'
          parent: false
          process_gcloudignore: false
